blank_issues_enabled: false
contact_links:
  - name: Official BDFR Site
    url: https://github.com/aliparlakci/bulk-downloader-for-reddit
    about: Site of the official bulk-downloader-for-reddit version
  - name: Official BDFR Discussions
    url: https://github.com/aliparlakci/bulk-downloader-for-reddit/discussions
    about: Discussions of the official version
  - name: Official BDFR Issues section
    url: https://github.com/aliparlakci/bulk-downloader-for-reddit/issues
    about: Issues section of the official version
